version: '3.8'

services:
  rabbit-mq:
    image: rabbitmq:3.9-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - '5672:5672'
      - '15672:15672'

  # billing:
  #   container_name: billing
  #   image: billing
  #   build: .
  #   depends_on:
  #     - rabbit-mq
  #   ports:
  #     - '4000:4000'
  
  # orders:
  #   container_name: orders
  #   image: orders
  #   build: .
  #   depends_on:
  #     - rabbit-mq
  #   ports:
  #     - '3000:3000'

  # auth:
  #   container_name: auth
  #   image: auth
  #   build: .
  #   depends_on:
  #     - rabbit-mq
  #   ports:
  #     - '3000:3000'